(async()=>{
  const me=await (await fetch('./api.php?action=me')).json(); if(!me.authenticated)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const load=async()=>{const r=await fetch('./api.php?action=admin_cases'),d=await r.json();if(!d.ok)return;const cases=d.requests||[];const active=cases.filter(c=>c.status!=='entregue').length;const metric=[...document.querySelectorAll('.metric-card strong')][0];if(metric)metric.textContent=active;const panel=[...document.querySelectorAll('.panel')].find(p=>p.querySelector('h3')?.textContent.includes('Atividade recente'));if(!panel)return;let live=panel.querySelector('.live-case-list');if(!live){live=document.createElement('div');live.className='case-list live-case-list';panel.append(live)}live.innerHTML=cases.map(c=>`<article class="case-row" data-live-code="${esc(c.code)}"><strong>${esc(c.service)}</strong><span>${esc(c.name)} • ${esc(c.code)}</span><span>${esc(c.status)} • ${esc(c.channel)}</span><button type="button" data-live-detail="${esc(c.code)}">Detalhes</button><button type="button" data-live-status="${esc(c.code)}">Avançar status</button></article>`).join('')||'<p>Nenhum pedido recebido ainda.</p>';live.querySelectorAll('[data-live-status]').forEach(b=>b.onclick=async()=>{const order=['novo','coleta','analise','aguardando','protocolado','exigencia','entregue'];const row=cases.find(c=>c.code===b.dataset.liveStatus);const next=order[Math.min(order.indexOf(row.status)+1,order.length-1)];await fetch('./api.php?action=admin_update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:row.code,status:next})});load()});live.querySelectorAll('[data-live-detail]').forEach(b=>b.onclick=async()=>{const d=await (await fetch('./api.php?action=admin_detail&code='+encodeURIComponent(b.dataset.liveDetail))).json();if(d.ok)alert(`${d.request.code} • ${d.request.name}\nStatus: ${d.request.status}\nResponsável: ${d.request.assigned_to||'não definido'}\n\nHistórico: ${d.events.map(x=>x.event+' - '+x.detail).join('; ')||'sem eventos'}\nDocumentos: ${d.documents.length}`)})};
  await load(); setInterval(load,15000);
  const logout=document.createElement('button');logout.textContent='Sair';logout.className='btn secondary small';logout.onclick=async()=>{await fetch('./api.php?action=logout',{method:'POST'});location.reload()};document.querySelector('.admin-top-actions')?.append(logout);
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!b.textContent.includes('Receber arquivo'))return;const code=prompt('Código do ticket (ex.: CD-1086):');if(!code)return;const input=document.createElement('input');input.type='file';input.accept='.pdf,.jpg,.jpeg,.png';input.onchange=async()=>{const f=new FormData();f.append('code',code);f.append('file',input.files[0]);const r=await fetch('./api.php?action=admin_document',{method:'POST',body:f});const d=await r.json();alert(d.message||'Documento recebido')};input.click()});
  document.addEventListener('submit',async e=>{if(e.target.id!=='newCaseForm')return;e.preventDefault();const f=e.target,fields=[...f.querySelectorAll('input,textarea,select')];await fetch('./api.php?action=request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields[0]?.value||'',phone:'Atendimento interno',service:fields[2]?.value||'outros',description:fields[1]?.value||'',channel:fields[1]?.value||'Atendimento humano'})});document.querySelector('dialog[open]')?.close();load()},true);
})();
