<?php
declare(strict_types=1);
session_name('cartorio_beta'); session_start();
header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
$dir=__DIR__.'/data'; if(!is_dir($dir)) mkdir($dir,0750,true);
$db=new PDO('sqlite:'.$dir.'/cartorio.sqlite'); $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$db->exec("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS requests (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,service TEXT NOT NULL,description TEXT,channel TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'novo',amount REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL,event TEXT NOT NULL,detail TEXT,username TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL,filename TEXT NOT NULL,path TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
foreach(['assigned_to TEXT','official_amount REAL NOT NULL DEFAULT 0','service_amount REAL NOT NULL DEFAULT 0'] as $col){try{$db->exec("ALTER TABLE requests ADD COLUMN $col");}catch(Throwable $e){}}
function out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE);exit;}
$action=$_GET['action']??'';
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='triage'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$problem=trim((string)($d['problem']??''));$services=is_array($d['services']??null)?$d['services']:[];if($problem==='')out(['ok'=>false,'message'=>'Descreva o caso.'],422);$prompt="Escolha até 3 serviços mais adequados. Responda somente JSON {\"ids\":[\"id\"]}. Caso: ".$problem."\nCatálogo: ".json_encode($services,JSON_UNESCAPED_UNICODE);$ch=curl_init('http://127.0.0.1:11434/api/generate');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode(['model'=>'qwen3:14b','prompt'=>$prompt,'stream'=>false,'format'=>'json']),CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>45]);$raw=curl_exec($ch);curl_close($ch);$j=json_decode((string)$raw,true);$answer=json_decode((string)($j['response']??''),true);if(!is_array($answer)||!is_array($answer['ids']??null))out(['ok'=>false,'message'=>'IA local indisponível.'],503);out(['ok'=>true,'ids'=>array_values(array_slice($answer['ids'],0,3))]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='login'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$s=$db->prepare('SELECT * FROM users WHERE username=?');$s->execute([trim((string)($d['username']??''))]);$u=$s->fetch(PDO::FETCH_ASSOC);if(!$u||!password_verify((string)($d['password']??''),$u['password_hash']))out(['ok'=>false,'message'=>'Usuário ou senha inválidos.'],401);$_SESSION['cartorio_user']=['id'=>$u['id'],'username'=>$u['username'],'role'=>$u['role']];out(['ok'=>true,'user'=>$_SESSION['cartorio_user']]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='logout'){session_destroy();out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='me'){out(['ok'=>true,'authenticated'=>!empty($_SESSION['cartorio_user']),'has_users'=>(int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn()>0,'user'=>$_SESSION['cartorio_user']??null]);}
if(in_array($action,['admin_cases','admin_update'],true)&&empty($_SESSION['cartorio_user']))out(['ok'=>false,'message'=>'Autenticação necessária.'],401);
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_cases'){out(['ok'=>true,'requests'=>$db->query('SELECT * FROM requests ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_clear_demo'){if(($_SESSION['cartorio_user']['role']??'')!=='admin')out(['ok'=>false,'message'=>'Apenas administradores podem limpar a base.'],403);$db->exec('DELETE FROM documents');$db->exec('DELETE FROM events');$db->exec('DELETE FROM requests');out(['ok'=>true,'message'=>'Base beta zerada.']);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_update'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$code=strtoupper(trim((string)($d['code']??'')));$s=$db->prepare('UPDATE requests SET status=COALESCE(NULLIF(?,\'\'),status),assigned_to=COALESCE(NULLIF(?,\'\'),assigned_to),official_amount=COALESCE(?,official_amount),service_amount=COALESCE(?,service_amount) WHERE code=?');$s->execute([(string)($d['status']??''),(string)($d['assigned_to']??''),$d['official_amount']??null,$d['service_amount']??null,$code]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$code,'Atualização','Status/responsável/valores atualizados',$_SESSION['cartorio_user']['username']??'']);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_detail'){$code=strtoupper(trim((string)($_GET['code']??'')));$s=$db->prepare('SELECT * FROM requests WHERE code=?');$s->execute([$code]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)out(['ok'=>false,'message'=>'Ticket não encontrado.'],404);$e=$db->prepare('SELECT * FROM events WHERE code=? ORDER BY id DESC');$e->execute([$code]);$f=$db->prepare('SELECT id,code,filename,created_at FROM documents WHERE code=? ORDER BY id DESC');$f->execute([$code]);out(['ok'=>true,'request'=>$r,'events'=>$e->fetchAll(PDO::FETCH_ASSOC),'documents'=>$f->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_document'){if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)out(['ok'=>false,'message'=>'Arquivo inválido.'],422);$code=strtoupper(trim((string)($_POST['code']??'')));$ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['pdf','jpg','jpeg','png'],true)||$_FILES['file']['size']>10*1024*1024)out(['ok'=>false,'message'=>'Aceitos PDF/JPG/PNG até 10 MB.'],422);$folder=$dir.'/uploads';if(!is_dir($folder))mkdir($folder,0750,true);$name=bin2hex(random_bytes(16)).'.'.$ext;$path=$folder.'/'.$name;if(!move_uploaded_file($_FILES['file']['tmp_name'],$path))out(['ok'=>false,'message'=>'Não foi possível guardar o arquivo.'],500);$s=$db->prepare('INSERT INTO documents(code,filename,path) VALUES(?,?,?)');$s->execute([$code,basename($_FILES['file']['name']),$name]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$code,'Documento','Arquivo recebido',$_SESSION['cartorio_user']['username']??'']);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='track'){$s=$db->prepare('SELECT code,name AS client,service,description,channel,status,amount,created_at FROM requests WHERE code=?');$s->execute([strtoupper(trim((string)($_GET['code']??'')))]);$r=$s->fetch(PDO::FETCH_ASSOC);out($r?['ok'=>true,'request'=>$r]:['ok'=>false,'message'=>'Pedido não encontrado.'],$r?200:404);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='request'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];foreach(['name','phone','service'] as $f)if(trim((string)($d[$f]??''))==='')out(['ok'=>false,'message'=>'Preencha nome, telefone e serviço.'],422);$n=(int)$db->query('SELECT COALESCE(MAX(id),1090)+1 FROM requests')->fetchColumn();$s=$db->prepare('INSERT INTO requests(code,name,phone,service,description,channel,status) VALUES(?,?,?,?,?,?,?)');$s->execute(['CD-'.$n,trim($d['name']),trim($d['phone']),trim($d['service']),trim((string)($d['description']??'')),trim((string)($d['channel']??'Site')),'novo']);out(['ok'=>true,'code'=>'CD-'.$n]);}
out(['ok'=>false,'message'=>'Ação inválida.'],404);
