<?php
declare(strict_types=1);
session_name('cartorio_beta'); session_start();
header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
$dir=__DIR__.'/data'; if(!is_dir($dir)) mkdir($dir,0750,true);
$db=new PDO('sqlite:'.$dir.'/cartorio.sqlite'); $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$db->exec("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'operator',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS requests (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,service TEXT NOT NULL,description TEXT,channel TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'novo',amount REAL NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL,event TEXT NOT NULL,detail TEXT,username TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL,filename TEXT NOT NULL,path TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
$db->exec("CREATE TABLE IF NOT EXISTS services (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");
foreach(['category TEXT','icon TEXT','kind TEXT','channel TEXT','docs_json TEXT','steps_json TEXT'] as $col){try{$db->exec("ALTER TABLE services ADD COLUMN $col");}catch(Throwable $e){}}
if((int)$db->query('SELECT COUNT(*) FROM services')->fetchColumn()===0){$seed=$db->prepare('INSERT INTO services(slug,title,description,price,active,category,icon,kind,channel,docs_json,steps_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)');foreach([['certidao-nascimento','Certidão de nascimento','Segunda via e localização do registro.',89,'civil','child_care'],['certidao-casamento','Certidão de casamento','Segunda via e pesquisa do cartório.',99,'civil','favorite'],['assinaturas','Reconhecimento de firma','Conferência e encaminhamento.',49,'notas','draw'],['autenticacao','Autenticação de cópias','Organização e encaminhamento.',49,'notas','verified'],['procuracoes','Procuração pública','Checklist e acompanhamento.',199,'notas','contract_edit'],['imoveis','Matrícula atualizada','Localização e solicitação.',149,'imoveis','home_work'],['pesquisa-matricula','Pesquisa de matrícula','Pesquisa pelos dados disponíveis.',149,'imoveis','travel_explore'],['protestos','Certidão de protesto','Pesquisa e obtenção de certidões.',99,'cobranca','gavel'],['notificacao-cobranca','Notificação de cobrança','Comunicação formal de dívida.',199,'cobranca','mark_email_unread'],['mediacao-geral','Mediação extrajudicial','Organização do diálogo entre as partes.',390,'mediacao','handshake']] as $v)$seed->execute([$v[0],$v[1],$v[2],$v[3],1,$v[4],$v[5],'assistido','CNJP','[]','[]']);}
foreach(['priority TEXT NOT NULL DEFAULT \'normal\'','deadline TEXT','notes TEXT','public_note TEXT','archived INTEGER NOT NULL DEFAULT 0'] as $col){try{$db->exec("ALTER TABLE requests ADD COLUMN $col");}catch(Throwable $e){}}
foreach(['assigned_to TEXT','official_amount REAL NOT NULL DEFAULT 0','service_amount REAL NOT NULL DEFAULT 0'] as $col){try{$db->exec("ALTER TABLE requests ADD COLUMN $col");}catch(Throwable $e){}}
function out(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE);exit;}
$cutoff=(new DateTimeImmutable('-365 days'))->format('Y-m-d H:i:s');$old=$db->prepare('SELECT id,code,path FROM documents WHERE created_at < ? AND path <> ""');$old->execute([$cutoff]);foreach($old->fetchAll(PDO::FETCH_ASSOC) as $doc){$file=$dir.'/uploads/'.basename((string)$doc['path']);if(is_file($file))unlink($file);$u=$db->prepare('UPDATE documents SET filename=?,path=? WHERE id=?');$u->execute(['[removido por retenção]','',(int)$doc['id']]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$doc['code'],'Retenção','Arquivo removido após prazo de retenção','sistema']);}
$action=$_GET['action']??'';
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='customer_login'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$code=strtoupper(trim((string)($d['code']??'')));$phone=preg_replace('/\D/','',(string)($d['phone']??''));$s=$db->prepare('SELECT * FROM requests WHERE code=? AND replace(replace(replace(replace(phone,"(",""),")", ""),"-","")," ","")=? AND archived=0');$s->execute([$code,$phone]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)out(['ok'=>false,'message'=>'Código ou telefone não conferem.'],401);$_SESSION['cartorio_customer']=['code'=>$r['code'],'phone'=>$phone];out(['ok'=>true,'code'=>$r['code']]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='customer_logout'){unset($_SESSION['cartorio_customer']);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='customer_portal'){if(empty($_SESSION['cartorio_customer']))out(['ok'=>false,'message'=>'Sessão do cliente não encontrada.'],401);$code=$_SESSION['cartorio_customer']['code'];$s=$db->prepare('SELECT code,name AS client,service,description,channel,status,amount,official_amount,service_amount,deadline,public_note,created_at FROM requests WHERE code=? AND archived=0');$s->execute([$code]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)out(['ok'=>false,'message'=>'Pedido não encontrado.'],404);$e=$db->prepare('SELECT event,detail,created_at FROM events WHERE code=? ORDER BY id ASC');$e->execute([$code]);$f=$db->prepare('SELECT filename,created_at FROM documents WHERE code=? AND path<>"" ORDER BY id DESC');$f->execute([$code]);out(['ok'=>true,'request'=>$r,'events'=>$e->fetchAll(PDO::FETCH_ASSOC),'documents'=>$f->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='triage'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$problem=trim((string)($d['problem']??''));$services=is_array($d['services']??null)?$d['services']:[];if($problem==='')out(['ok'=>false,'message'=>'Descreva o caso.'],422);$prompt="Analise o caso com atenção. Escolha somente serviços diretamente relacionados ao problema. Responda somente JSON {\"ids\":[\"id\"],\"explanation\":\"2 frases específicas com o que aconteceu e os próximos passos\"}. Caso: ".$problem."\nCatálogo: ".json_encode($services,JSON_UNESCAPED_UNICODE);$ch=curl_init('http://127.0.0.1:11434/api/generate');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode(['model'=>'llama3.2:3b','prompt'=>$prompt,'stream'=>false,'format'=>'json','keep_alive'=>'10m','options'=>['temperature'=>0.2,'num_predict'=>180]]),CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>60]);$raw=curl_exec($ch);curl_close($ch);$j=json_decode((string)$raw,true);$answer=json_decode((string)($j['response']??''),true);if(!is_array($answer)||!is_array($answer['ids']??null))out(['ok'=>false,'message'=>'IA local indisponível.'],503);out(['ok'=>true,'ids'=>array_values(array_slice($answer['ids'],0,3)),'explanation'=>trim((string)($answer['explanation']??''))]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='login'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$s=$db->prepare('SELECT * FROM users WHERE username=?');$s->execute([trim((string)($d['username']??''))]);$u=$s->fetch(PDO::FETCH_ASSOC);if(!$u||!password_verify((string)($d['password']??''),$u['password_hash']))out(['ok'=>false,'message'=>'Usuário ou senha inválidos.'],401);$_SESSION['cartorio_user']=['id'=>$u['id'],'username'=>$u['username'],'role'=>$u['role']];out(['ok'=>true,'user'=>$_SESSION['cartorio_user']]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='logout'){session_destroy();out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='me'){out(['ok'=>true,'authenticated'=>!empty($_SESSION['cartorio_user']),'has_users'=>(int)$db->query('SELECT COUNT(*) FROM users')->fetchColumn()>0,'user'=>$_SESSION['cartorio_user']??null]);}
if(in_array($action,['admin_cases','admin_update','admin_detail','admin_document','admin_seed_demo','admin_clear_demo','admin_create','admin_users','admin_user_save','admin_service_save','admin_services','admin_report','admin_backup','admin_policy'],true)&&empty($_SESSION['cartorio_user']))out(['ok'=>false,'message'=>'Autenticação necessária.'],401);
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_users'){out(['ok'=>true,'users'=>$db->query('SELECT id,username,role,created_at FROM users ORDER BY username')->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_user_save'){if(($_SESSION['cartorio_user']['role']??'')!=='admin')out(['ok'=>false,'message'=>'Apenas administradores.'],403);$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$u=trim((string)($d['username']??''));$p=(string)($d['password']??'');$role=in_array($d['role']??'', ['admin','operator','attendant'],true)?$d['role']:'operator';if($u===''||($p!==''&&strlen($p)<8))out(['ok'=>false,'message'=>'Usuário inválido ou senha curta.'],422);if(!empty($d['id'])){$s=$p!==''?$db->prepare('UPDATE users SET username=?,role=?,password_hash=? WHERE id=?'):$db->prepare('UPDATE users SET username=?,role=? WHERE id=?');$p!==''?$s->execute([$u,$role,password_hash($p,PASSWORD_DEFAULT),(int)$d['id']]):$s->execute([$u,$role,(int)$d['id']]);}else{$s=$db->prepare('INSERT INTO users(username,role,password_hash) VALUES(?,?,?)');$s->execute([$u,$role,password_hash($p,PASSWORD_DEFAULT)]);}out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_services'){out(['ok'=>true,'services'=>$db->query('SELECT * FROM services ORDER BY title')->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='services_public'){out(['ok'=>true,'services'=>$db->query('SELECT slug AS id,title,description AS desc,price AS "from",category,icon,kind,channel,docs_json,steps_json FROM services WHERE active=1 ORDER BY title')->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_service_save'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$title=trim((string)($d['title']??''));$slug=trim((string)($d['slug']??preg_replace('/[^a-z0-9]+/i','-',strtolower($title))));if($title===''||$slug==='')out(['ok'=>false,'message'=>'Título obrigatório.'],422);if(!empty($d['id'])){$s=$db->prepare('UPDATE services SET slug=?,title=?,description=?,price=?,active=? WHERE id=?');$s->execute([$slug,$title,trim((string)($d['description']??'')),(float)($d['price']??0),!empty($d['active'])?1:0,(int)$d['id']]);}else{$s=$db->prepare('INSERT INTO services(slug,title,description,price,active) VALUES(?,?,?,?,?)');$s->execute([$slug,$title,trim((string)($d['description']??'')),(float)($d['price']??0),1]);}out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_report'){$r=$db->query("SELECT status,COUNT(*) total,COALESCE(SUM(amount),0) amount FROM requests WHERE archived=0 GROUP BY status")->fetchAll(PDO::FETCH_ASSOC);out(['ok'=>true,'by_status'=>$r,'total'=>(int)$db->query('SELECT COUNT(*) FROM requests WHERE archived=0')->fetchColumn(),'amount'=>(float)$db->query('SELECT COALESCE(SUM(amount),0) FROM requests WHERE archived=0')->fetchColumn()]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_backup'){if(($_SESSION['cartorio_user']['role']??'')!=='admin')out(['ok'=>false,'message'=>'Apenas administradores.'],403);$dump=[];foreach(['users','requests','events','documents','services'] as $t)$dump[$t]=$db->query("SELECT * FROM $t")->fetchAll(PDO::FETCH_ASSOC);header('Content-Disposition: attachment; filename=cartorio-backup-'.date('Ymd-His').'.json');out(['exported_at'=>date(DATE_ATOM),'data'=>$dump]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_policy'){out(['ok'=>true,'policy'=>['max_upload_mb'=>10,'allowed_types'=>['pdf','jpg','jpeg','png'],'retention_days'=>365,'access'=>'authenticated_staff']]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_cases'){out(['ok'=>true,'requests'=>$db->query('SELECT * FROM requests WHERE archived=0 ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_create'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];foreach(['name','phone','service'] as $f)if(trim((string)($d[$f]??''))==='')out(['ok'=>false,'message'=>'Nome, telefone e serviço são obrigatórios.'],422);$n=(int)$db->query('SELECT COALESCE(MAX(id),1090)+1 FROM requests')->fetchColumn();$code='CD-'.$n;$s=$db->prepare('INSERT INTO requests(code,name,phone,service,description,channel,status,priority,deadline,notes,amount,official_amount,service_amount,assigned_to) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$code,trim($d['name']),trim($d['phone']),trim($d['service']),trim((string)($d['description']??'')),trim((string)($d['channel']??'Admin')),'novo',trim((string)($d['priority']??'normal')),trim((string)($d['deadline']??'')),trim((string)($d['notes']??'')),(float)($d['amount']??0),(float)($d['official_amount']??0),(float)($d['service_amount']??0),trim((string)($d['assigned_to']??''))]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$code,'Criação','Ticket criado no painel',$_SESSION['cartorio_user']['username']]);out(['ok'=>true,'code'=>$code]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_clear_demo'){if(($_SESSION['cartorio_user']['role']??'')!=='admin')out(['ok'=>false,'message'=>'Apenas administradores podem limpar a base.'],403);$db->exec('DELETE FROM documents');$db->exec('DELETE FROM events');$db->exec('DELETE FROM requests');out(['ok'=>true,'message'=>'Base beta zerada.']);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_seed_demo'){if(($_SESSION['cartorio_user']['role']??'')!=='admin')out(['ok'=>false,'message'=>'Apenas administradores podem cadastrar testes.'],403);$rows=[['Teste Beta - Ana','(11) 90000-0001','Certidão de nascimento','Site','novo',89],['Teste Beta - Bruno','(11) 90000-0002','Reconhecimento de firma','Balcão','coleta',49],['Teste Beta - Carla','(11) 90000-0003','Matrícula atualizada','WhatsApp','analise',299],['Teste Beta - Diego','(11) 90000-0004','Mediação extrajudicial','Site','aguardando',790],['Teste Beta - Elisa','(11) 90000-0005','Notificação extrajudicial','Telefone','protocolado',690]];$s=$db->prepare('INSERT INTO requests(code,name,phone,service,description,channel,status,amount,official_amount,service_amount,assigned_to) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$i=0;foreach($rows as $row){$code='BETA-'.date('ymd').'-'.(++$i);$s->execute([$code,$row[0],$row[1],$row[2],'Registro sintético para teste do sistema.',$row[3],$row[4],$row[5],round($row[5]*.4,2),round($row[5]*.6,2),$_SESSION['cartorio_user']['username']]);$e->execute([$code,'Criação','Ticket de teste cadastrado pelo sistema',$_SESSION['cartorio_user']['username']]);}out(['ok'=>true,'created'=>count($rows)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_update'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$code=strtoupper(trim((string)($d['code']??'')));$s=$db->prepare('UPDATE requests SET name=COALESCE(NULLIF(?,\'\'),name),phone=COALESCE(NULLIF(?,\'\'),phone),service=COALESCE(NULLIF(?,\'\'),service),status=COALESCE(NULLIF(?,\'\'),status),assigned_to=COALESCE(NULLIF(?,\'\'),assigned_to),priority=COALESCE(NULLIF(?,\'\'),priority),deadline=COALESCE(NULLIF(?,\'\'),deadline),notes=COALESCE(NULLIF(?,\'\'),notes),public_note=COALESCE(NULLIF(?,\'\'),public_note),official_amount=COALESCE(?,official_amount),service_amount=COALESCE(?,service_amount),amount=COALESCE(?,amount) WHERE code=?');$s->execute([(string)($d['name']??''),(string)($d['phone']??''),(string)($d['service']??''),(string)($d['status']??''),(string)($d['assigned_to']??''),(string)($d['priority']??''),(string)($d['deadline']??''),(string)($d['notes']??''),(string)($d['public_note']??''),$d['official_amount']??null,$d['service_amount']??null,$d['amount']??null,$code]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$code,'Atualização','Ticket atualizado',$_SESSION['cartorio_user']['username']??'']);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_archive'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];$s=$db->prepare('UPDATE requests SET archived=1 WHERE code=?');$s->execute([strtoupper(trim((string)($d['code']??'')))]);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='admin_detail'){$code=strtoupper(trim((string)($_GET['code']??'')));$s=$db->prepare('SELECT * FROM requests WHERE code=?');$s->execute([$code]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)out(['ok'=>false,'message'=>'Ticket não encontrado.'],404);$e=$db->prepare('SELECT * FROM events WHERE code=? ORDER BY id DESC');$e->execute([$code]);$f=$db->prepare('SELECT id,code,filename,created_at FROM documents WHERE code=? ORDER BY id DESC');$f->execute([$code]);out(['ok'=>true,'request'=>$r,'events'=>$e->fetchAll(PDO::FETCH_ASSOC),'documents'=>$f->fetchAll(PDO::FETCH_ASSOC)]);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='admin_document'){if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)out(['ok'=>false,'message'=>'Arquivo inválido.'],422);$code=strtoupper(trim((string)($_POST['code']??'')));$ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION));if(!in_array($ext,['pdf','jpg','jpeg','png'],true)||$_FILES['file']['size']>10*1024*1024)out(['ok'=>false,'message'=>'Aceitos PDF/JPG/PNG até 10 MB.'],422);$folder=$dir.'/uploads';if(!is_dir($folder))mkdir($folder,0750,true);$name=bin2hex(random_bytes(16)).'.'.$ext;$path=$folder.'/'.$name;if(!move_uploaded_file($_FILES['file']['tmp_name'],$path))out(['ok'=>false,'message'=>'Não foi possível guardar o arquivo.'],500);$s=$db->prepare('INSERT INTO documents(code,filename,path) VALUES(?,?,?)');$s->execute([$code,basename($_FILES['file']['name']),$name]);$e=$db->prepare('INSERT INTO events(code,event,detail,username) VALUES(?,?,?,?)');$e->execute([$code,'Documento','Arquivo recebido',$_SESSION['cartorio_user']['username']??'']);out(['ok'=>true]);}
if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='track'){$s=$db->prepare('SELECT code,name AS client,service,description,channel,status,amount,created_at FROM requests WHERE code=?');$s->execute([strtoupper(trim((string)($_GET['code']??'')))]);$r=$s->fetch(PDO::FETCH_ASSOC);out($r?['ok'=>true,'request'=>$r]:['ok'=>false,'message'=>'Pedido não encontrado.'],$r?200:404);}
if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='request'){$d=json_decode(file_get_contents('php://input')?:'{}',true)?:[];foreach(['name','phone','service'] as $f)if(trim((string)($d[$f]??''))==='')out(['ok'=>false,'message'=>'Preencha nome, telefone e serviço.'],422);$n=(int)$db->query('SELECT COALESCE(MAX(id),1090)+1 FROM requests')->fetchColumn();$s=$db->prepare('INSERT INTO requests(code,name,phone,service,description,channel,status) VALUES(?,?,?,?,?,?,?)');$s->execute(['CD-'.$n,trim($d['name']),trim($d['phone']),trim($d['service']),trim((string)($d['description']??'')),trim((string)($d['channel']??'Site')),'novo']);out(['ok'=>true,'code'=>'CD-'.$n]);}
out(['ok'=>false,'message'=>'Ação inválida.'],404);
