import { SERVICES, CASES, STATUS, AUTOMATIONS } from './data.js';

const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const toast=(msg)=>{const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)};
const icon=n=>`<span class="material-symbols-rounded">${n}</span>`;
const serviceBy=id=>SERVICES.find(s=>s.id===id)||SERVICES.at(-1);

if(document.body.dataset.page==='client') initClient();
if(document.body.dataset.page==='admin') initAdmin();

function initClient(){
  const grid=$('#serviceGrid'),modal=$('#flowModal'),content=$('#flowContent');
  grid.innerHTML=SERVICES.map(s=>`<article class="service-card" data-service="${s.id}"><span class="service-icon material-symbols-rounded">${s.icon}</span><strong>${s.title}</strong><p>${s.desc}</p><div class="service-meta"><span>${s.from?`a partir de ${money(s.from)}`:'triagem gratuita'}</span><b>Começar →</b></div></article>`).join('');
  const open=html=>{content.innerHTML=html;modal.showModal()};const close=()=>modal.close();
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  modal.addEventListener('click',e=>{if(e.target===modal)close()});
  grid.addEventListener('click',e=>{const card=e.target.closest('[data-service]');if(card)showService(card.dataset.service)});
  $$('[data-start-triage]').forEach(b=>b.addEventListener('click',showTriage));
  $$('[data-human]').forEach(b=>b.addEventListener('click',showHuman));
  $$('[data-track]').forEach(b=>b.addEventListener('click',()=>showTracking('CD-1086')));
  $('#trackForm')?.addEventListener('submit',e=>{e.preventDefault();showTracking(e.currentTarget.querySelector('input').value.trim().toUpperCase())});

  function showTriage(){open(`<div class="flow-inner"><span class="kicker">Triagem inteligente</span><h2>O que você precisa resolver?</h2><p>Não precisa conhecer o nome técnico. Escolha o assunto mais parecido ou conte o problema para uma pessoa.</p><div class="flow-options">${SERVICES.map(s=>`<button class="flow-option" data-pick="${s.id}">${icon(s.icon)}<span><strong>${s.title}</strong><small>${s.desc}</small></span></button>`).join('')}</div></div>`);$$('[data-pick]',content).forEach(b=>b.addEventListener('click',()=>showService(b.dataset.pick)))}
  function showService(id){const s=serviceBy(id);open(`<div class="flow-inner"><span class="kicker">${s.channel}</span><h2>${s.title}</h2><p>${s.desc}</p><div class="case-section"><h3>Para começar, normalmente precisamos de:</h3>${s.docs.map(d=>`<div class="doc-line"><span>${d}</span><span class="ok">vamos conferir</span></div>`).join('')}</div><form id="clientFlow" class="flow-form"><div class="field"><label>Seu nome</label><input required placeholder="Como podemos te chamar?"></div><div class="field"><label>WhatsApp ou telefone</label><input required placeholder="(11) 99999-9999"></div><div class="field"><label>Conte o que aconteceu</label><textarea placeholder="Explique do seu jeito. Ex.: preciso reconhecer a assinatura num documento e não sei onde ir."></textarea></div><div class="field"><label>Como prefere continuar?</label><select><option>Quero fazer tudo online</option><option>Quero falar com uma pessoa</option><option>Prefiro atendimento presencial</option><option>Prefiro telefone</option></select></div><div class="flow-actions"><button type="button" class="btn secondary" data-back>Voltar</button><button class="btn primary" type="submit">Criar pedido simulado</button></div></form></div>`);$('[data-back]',content).addEventListener('click',showTriage);$('#clientFlow').addEventListener('submit',e=>{e.preventDefault();content.innerHTML=`<div class="flow-inner"><span class="kicker">Pedido simulado criado</span><h2>Pronto. Agora isso virou um processo, não uma conversa perdida.</h2><p>Numa versão real, os dados entrariam automaticamente no painel administrativo e um atendente validaria o checklist antes de qualquer protocolo.</p><div class="track-summary"><div><span>Pedido</span><strong>CD-1091</strong></div><div><span>Serviço</span><strong>${s.title}</strong></div><div><span>Canal</span><strong>Triagem digital</strong></div><div><span>Status</span><strong>Recebido</strong></div></div><div class="flow-actions"><button class="btn primary" data-finish>Entendi</button></div></div>`;$('[data-finish]',content).addEventListener('click',()=>{close();toast('Simulação enviada para a operação')})})}
  function showHuman(){open(`<div class="flow-inner"><span class="kicker">Atendimento humano</span><h2>Escolha o jeito mais confortável.</h2><p>O cliente não precisa virar operador de sistema. Nossa equipe usa a tecnologia nos bastidores.</p><div class="human-channels"><article>${icon('chat')}<div><strong>WhatsApp com atendente</strong><span>Uma pessoa conversa, pede fotos e cria o processo.</span></div></article><article>${icon('call')}<div><strong>Telefone</strong><span>Para quem prefere explicar falando. A equipe preenche tudo.</span></div></article><article>${icon('storefront')}<div><strong>Balcão presencial</strong><span>Chegou com papel amassado na sacola? A gente organiza.</span></div></article><article>${icon('home_health')}<div><strong>Atendimento assistido</strong><span>Opção futura para idosos, pessoas com dificuldade digital ou casos especiais.</span></div></article></div><div class="flow-actions"><button class="btn primary" data-human-demo>Simular Seu João no balcão</button></div></div>`);$('[data-human-demo]',content).addEventListener('click',()=>{content.innerHTML=`<div class="flow-inner"><span class="kicker">Atendimento humano assistido</span><h2>Seu João, 83 anos</h2><p>Ele só quer reconhecer firma. O atendente faz perguntas curtas, fotografa/digitaliza o necessário e o sistema monta o checklist por trás.</p><div class="case-section"><div class="doc-line"><span>RG apresentado</span><span class="ok">✓ conferido</span></div><div class="doc-line"><span>Documento que será assinado</span><span class="waiting">aguardando original</span></div><div class="doc-line"><span>Telefone do filho</span><span class="ok">✓ anotado</span></div></div><div class="track-summary"><div><span>Taxa oficial estimada</span><strong>${money(28)}</strong></div><div><span>Serviço CNJP</span><strong>${money(50)}</strong></div><div><span>Total simulado</span><strong>${money(78)}</strong></div><div><span>Pagamento</span><strong>dinheiro / Pix / cartão</strong></div></div><div class="flow-actions"><button class="btn primary" data-finish>Enviar para operação</button></div></div>`;$('[data-finish]',content).addEventListener('click',()=>{close();toast('Seu João entrou na fila operacional')})})}
  function showTracking(id){const c=CASES.find(x=>x.id===id)||CASES[1],st=STATUS[c.status];open(`<div class="flow-inner"><span class="kicker">Acompanhamento</span><h2>${c.id} • ${c.title}</h2><p>${c.client} • ${c.channel}</p><div class="track-summary"><div><span>Status</span><strong>${st.label}</strong></div><div><span>Responsável</span><strong>${c.owner}</strong></div><div><span>Total</span><strong>${money(c.amount)}</strong></div><div><span>Prazo estimado</span><strong>${c.deadline}</strong></div></div><div class="case-section"><h3>Linha do tempo</h3><div class="timeline">${c.timeline.map((t,i)=>`<div class="${i<c.timeline.length-1?'done':'active'}">${t}</div>`).join('')}</div></div><div class="flow-actions"><button class="btn secondary" data-close-inner>Fechar</button></div></div>`);$('[data-close-inner]',content).addEventListener('click',close)}
}

function initAdmin(){
  const content=$('#adminContent'),nav=$('#adminNav'),caseModal=$('#caseModal'),caseContent=$('#caseContent');let active='dashboard';
  const titles={dashboard:['Visão geral','Operação de hoje, sem planilha voando pela sala.'],atendimentos:['Atendimentos','Todos os clientes, digitais e humanos, na mesma fila.'],kanban:['Processos','Do primeiro contato até a entrega final.'],triagem:['Central de triagem','Entradas digitais, WhatsApp, telefone e balcão.'],documentos:['Documentos','Arquivos recebidos, conferidos, faltantes e entregues.'],financeiro:['Financeiro','Taxa oficial separada do serviço da CNJP.'],servicos:['Catálogo de serviços','Receitas operacionais que ensinam a equipe a executar.'],automacoes:['Automações','Tecnologia trabalhando sem expulsar o humano da operação.'],base:['Base operacional','Conhecimento transformado em checklist, fluxo e padrão.']};
  nav.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('[data-view]',nav).forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.view;render();$('.admin-sidebar').classList.remove('open')});
  $('#menuToggle').addEventListener('click',()=>$('.admin-sidebar').classList.toggle('open'));
  $('#simulateHuman').addEventListener('click',()=>openNew('human'));$('#simulateDigital').addEventListener('click',()=>openNew('digital'));
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));caseModal.addEventListener('click',e=>{if(e.target===caseModal)caseModal.close()});
  function render(){const [t,s]=titles[active];$('#viewTitle').textContent=t;$('#viewSubtitle').textContent=s;content.innerHTML=active==='dashboard'?dashboard():active==='atendimentos'?atendimentos():active==='kanban'?kanban():active==='triagem'?triagem():active==='documentos'?documentos():active==='financeiro'?financeiro():active==='servicos'?servicos():active==='automacoes'?automacoes():base();bindCases()}
  function dashboard(){const open=CASES.filter(c=>c.status!=='entregue').length,total=CASES.reduce((a,c)=>a+c.amount,0),fees=CASES.reduce((a,c)=>a+c.fee,0);return `<section class="dashboard-grid"><article class="metric-card"><span>Processos ativos</span><strong>${open}</strong><small class="good">2 com movimentação hoje</small></article><article class="metric-card"><span>Aguardando cliente</span><strong>2</strong><small>documentos ou informação</small></article><article class="metric-card"><span>Recebido / previsto</span><strong>${money(total)}</strong><small>inclui taxas oficiais</small></article><article class="metric-card"><span>Receita operacional</span><strong>${money(fees)}</strong><small class="good">serviço CNJP separado</small></article><article class="panel span2"><div class="panel-head"><div><h3>Fila de atenção</h3><p>Prioridades, exigências e prazos próximos.</p></div><button class="link-btn" data-go="atendimentos">ver todos</button></div><div class="case-list">${CASES.filter(c=>c.priority==='high'||c.status==='exigencia').map(caseRow).join('')}</div></article><article class="panel span2"><div class="panel-head"><div><h3>Ações rápidas</h3><p>Os caminhos que a equipe mais usa.</p></div></div><div class="quick-grid"><button class="quick-action" data-new-human>${icon('person_add')}<strong>Atendimento humano</strong><span>Balcão, telefone ou WhatsApp</span></button><button class="quick-action" data-new-digital>${icon('auto_awesome')}<strong>Triagem digital</strong><span>Simular entrada do site</span></button><button class="quick-action" data-go="documentos">${icon('document_scanner')}<strong>Conferir documentos</strong><span>3 pendências</span></button><button class="quick-action" data-go="kanban">${icon('view_kanban')}<strong>Abrir processos</strong><span>Visão por etapa</span></button></div></article><article class="panel span4"><div class="panel-head"><div><h3>Atividade recente</h3><p>Uma linha operacional única, independente do canal do cliente.</p></div></div><div class="case-list">${CASES.slice(0,5).map(caseRow).join('')}</div></article></section>`}
  function atendimentos(){return `<div class="filter-row"><button class="active">Todos</button><button>Digitais</button><button>Humanos</button><button>Exigências</button><button>Prazo próximo</button><button>Concluídos</button></div><section class="panel"><div class="panel-head"><div><h3>Fila unificada</h3><p>Site, balcão, telefone e WhatsApp terminam no mesmo lugar.</p></div><button class="btn primary small" data-new-human>${icon('add')}Novo</button></div><div class="case-list">${CASES.map(caseRow).join('')}</div></section>`}
  function kanban(){const columns=['coleta','analise','aguardando','protocolado','exigencia','entregue'];return `<div class="kanban">${columns.map(st=>{const arr=CASES.filter(c=>c.status===st);return `<section class="kanban-col"><header class="kanban-head"><span>${STATUS[st].label}</span><b>${arr.length}</b></header>${arr.length?arr.map(c=>`<article class="kanban-card" data-case="${c.id}"><strong>${c.title}</strong><span>${c.client}</span><span>${c.id} • ${c.channel}</span><footer><span>${c.owner}</span><span>${money(c.amount)}</span></footer></article>`).join(''):'<div class="kanban-card"><span>Nenhum processo aqui</span></div>'}</section>`}).join('')}</div>`}
  function triagem(){return `<section class="dashboard-grid"><article class="panel span2"><div class="panel-head"><div><h3>Entrada digital</h3><p>Cliente responde sozinho, sistema sugere o caminho.</p></div></div><div class="quick-grid"><button class="quick-action" data-new-digital>${icon('auto_awesome')}<strong>Simular triagem</strong><span>Fluxo do site</span></button><button class="quick-action">${icon('chat')}<strong>WhatsApp</strong><span>3 conversas abertas</span></button><button class="quick-action">${icon('document_scanner')}<strong>OCR</strong><span>Extrair dados de arquivo</span></button><button class="quick-action">${icon('psychology')}<strong>IA assistida</strong><span>Sugerir checklist</span></button></div></article><article class="panel span2"><div class="panel-head"><div><h3>Entrada humana</h3><p>O operador preenche o sistema enquanto conversa.</p></div></div><div class="quick-grid"><button class="quick-action" data-new-human>${icon('storefront')}<strong>Balcão</strong><span>Seu João chegou</span></button><button class="quick-action" data-new-human>${icon('call')}<strong>Telefone</strong><span>Criar durante ligação</span></button><button class="quick-action" data-new-human>${icon('record_voice_over')}<strong>Atendimento assistido</strong><span>Sem exigir habilidade digital</span></button><button class="quick-action">${icon('print')}<strong>Digitalizar</strong><span>Papel vira arquivo do caso</span></button></div></article><article class="panel span4"><div class="panel-head"><div><h3>Regra da casa</h3><p>A tecnologia se adapta ao cliente, não o contrário.</p></div></div><p style="font-size:.7rem;color:#667085">A mesma estrutura de dados recebe uma solicitação digitada no celular por uma pessoa de 25 anos ou preenchida por um atendente enquanto um senhor de 83 anos explica o caso no balcão. Depois da triagem, a operação é idêntica.</p></article></section>`}
  function documentos(){const docs=CASES.flatMap(c=>c.docs.map(([name,state])=>({name,state,c})));return `<section class="panel"><div class="panel-head"><div><h3>Central documental</h3><p>O operador sabe exatamente o que chegou e o que ainda falta.</p></div><button class="btn secondary small">${icon('upload_file')}Receber arquivo</button></div><div class="docs-grid">${docs.map(d=>`<article class="doc-card" data-case="${d.c.id}">${icon(d.state==='ok'?'draft':d.state==='missing'?'error':'schedule')}<div><strong>${d.name}</strong><span>${d.c.id} • ${d.c.client}</span><span>${d.state==='ok'?'Conferido':d.state==='missing'?'Faltando':'Aguardando'}</span></div></article>`).join('')}</div></section>`}
  function financeiro(){const official=CASES.reduce((a,c)=>a+c.official,0),fees=CASES.reduce((a,c)=>a+c.fee,0);return `<div class="finance-summary"><div><span>Total movimentado</span><strong>${money(official+fees)}</strong></div><div><span>Taxas oficiais</span><strong>${money(official)}</strong></div><div><span>Serviços CNJP</span><strong>${money(fees)}</strong></div><div><span>Pendentes</span><strong>${money(430)}</strong></div></div><section class="panel"><div class="panel-head"><div><h3>Composição por pedido</h3><p>Nunca misturar emolumento com receita da empresa.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Serviço</th><th>Taxa oficial</th><th>CNJP</th><th>Total</th></tr></thead><tbody>${CASES.map(c=>`<tr data-case="${c.id}"><td><strong>${c.id}</strong></td><td>${c.client}</td><td>${c.title}</td><td>${money(c.official)}</td><td>${money(c.fee)}</td><td><strong>${money(c.amount)}</strong></td></tr>`).join('')}</tbody></table></div></section>`}
  function servicos(){return `<section class="service-admin-grid">${SERVICES.map(s=>`<article class="admin-service-card"><header>${icon(s.icon)}<div><strong>${s.title}</strong><div class="tag">${s.channel}</div></div></header><p>${s.desc}</p><strong style="font-size:.58rem">Checklist base</strong><ul>${s.docs.map(x=>`<li>${x}</li>`).join('')}</ul><strong style="font-size:.58rem">Workflow</strong><p>${s.steps.join(' → ')}</p><button class="link-btn">Editar receita operacional</button></article>`).join('')}</section>`}
  function automacoes(){return `<section class="automation-grid">${AUTOMATIONS.map(([t,d,s])=>`<article class="automation-card"><div><strong>${t}</strong><span>${d}</span></div><span class="auto-state">${s}</span></article>`).join('')}</section>`}
  function base(){return `<section class="knowledge-grid"><article class="knowledge-card"><strong>Como identificar a serventia competente?</strong><p>Árvore de decisão por tipo de ato, local, circunscrição e dados disponíveis.</p><button class="link-btn">Abrir artigo</button></article><article class="knowledge-card"><strong>Checklist: certidão de casamento</strong><p>Campos obrigatórios, alternativas quando o cliente não sabe o cartório e roteiro de pesquisa.</p><button class="link-btn">Abrir checklist</button></article><article class="knowledge-card"><strong>Nota de exigência: como tratar</strong><p>Registrar documento, prazo, responsável, resumo e itens exigidos antes de falar com o cliente.</p><button class="link-btn">Abrir procedimento</button></article><article class="knowledge-card"><strong>Atendimento de idosos e baixa familiaridade digital</strong><p>Roteiro curto, linguagem simples, confirmação verbal e operação totalmente assistida.</p><button class="link-btn">Abrir roteiro</button></article><article class="knowledge-card"><strong>Separação de valores</strong><p>Como mostrar taxa oficial, despesas de terceiro e serviço CNJP em orçamento e recibo.</p><button class="link-btn">Abrir regra</button></article><article class="knowledge-card"><strong>Segurança documental</strong><p>Acesso mínimo, registro de atividades, prazo de retenção e descarte de documentos.</p><button class="link-btn">Abrir política</button></article></section>`}
  function caseRow(c){return `<article class="case-row" data-case="${c.id}"><div><strong>${c.title}</strong><span>${c.client} • ${c.id}</span><div class="case-tags"><span class="tag ${c.priority==='high'?'high':''}">${STATUS[c.status].label}</span><span class="tag ${c.channel.includes('Balcão')||c.channel==='Telefone'?'human':''}">${c.channel}</span></div></div><div><span class="money">${money(c.amount)}</span><span>${c.deadline}</span></div></article>`}
  function bindCases(){$$('[data-case]',content).forEach(el=>el.addEventListener('click',()=>openCase(el.dataset.case)));$$('[data-go]',content).forEach(b=>b.addEventListener('click',()=>{$(`[data-view="${b.dataset.go}"]`,nav)?.click()}));$$('[data-new-human]',content).forEach(b=>b.addEventListener('click',()=>openNew('human')));$$('[data-new-digital]',content).forEach(b=>b.addEventListener('click',()=>openNew('digital')))}
  function openCase(id){const c=CASES.find(x=>x.id===id);if(!c)return;const st=STATUS[c.status];caseContent.innerHTML=`<div class="case-inner"><div class="case-header"><span class="kicker">${c.id}</span><h2>${c.title}</h2><p>${c.client} • ${c.phone}</p><div class="case-badges"><span class="status-pill ${c.status==='exigencia'?'warning':c.status==='entregue'?'success':''}">${icon(st.icon)}${st.label}</span><span class="status-pill">${c.channel}</span><span class="status-pill">Responsável: ${c.owner}</span></div></div><div class="case-grid"><section class="case-section"><h3>Resumo operacional</h3><div class="case-data"><div><span>Prazo</span><strong>${c.deadline}</strong></div><div><span>Criado</span><strong>${c.created}</strong></div><div><span>Taxa oficial</span><strong>${money(c.official)}</strong></div><div><span>Serviço CNJP</span><strong>${money(c.fee)}</strong></div></div><p style="font-size:.58rem;color:#667085;margin-top:10px">${c.notes}</p></section><section class="case-section"><h3>Checklist documental</h3>${c.docs.map(([d,s])=>`<div class="doc-line"><span>${d}</span><span class="${s}">${s==='ok'?'✓ conferido':s==='missing'?'faltando':'aguardando'}</span></div>`).join('')}</section><section class="case-section"><h3>Linha do tempo</h3><div class="timeline">${c.timeline.map((t,i)=>`<div class="${i<c.timeline.length-1?'done':'active'}">${t}</div>`).join('')}</div></section><section class="case-section"><h3>Próximas ações</h3><div class="case-actions"><button class="primary">Atualizar status</button><button>Enviar WhatsApp</button><button>Adicionar documento</button><button>Registrar protocolo</button><button>Adicionar despesa</button><button>Gerar comprovante</button></div></section></div></div>`;caseModal.showModal()}
  function openNew(type){caseContent.innerHTML=`<div class="case-inner"><span class="kicker">${type==='human'?'Atendimento humano assistido':'Triagem digital simulada'}</span><h2>${type==='human'?'Criar processo enquanto conversa':'Simular nova entrada do site'}</h2><p>${type==='human'?'O cliente fala. O operador transforma a conversa em dados estruturados.':'O cliente preenche sozinho e o sistema prepara o caso para revisão humana.'}</p><form id="newCaseForm" class="flow-form"><div class="field"><label>Cliente</label><input required value="${type==='human'?'João da Silva':''}" placeholder="Nome"></div><div class="field"><label>Canal</label><select><option>${type==='human'?'Balcão presencial':'Triagem digital'}</option><option>WhatsApp</option><option>Telefone</option></select></div><div class="field"><label>O que precisa resolver?</label><textarea placeholder="Pode escrever em linguagem normal.">${type==='human'?'Quero reconhecer firma neste documento.':''}</textarea></div><div class="field"><label>Serviço sugerido</label><select>${SERVICES.map(s=>`<option ${type==='human'&&s.id==='assinaturas'?'selected':''}>${s.title}</option>`).join('')}</select></div><div class="flow-actions"><button type="button" class="btn secondary" data-cancel>Cancelar</button><button class="btn primary" type="submit">Criar caso simulado</button></div></form></div>`;caseModal.showModal();$('[data-cancel]',caseContent).addEventListener('click',()=>caseModal.close());$('#newCaseForm',caseContent).addEventListener('submit',e=>{e.preventDefault();caseModal.close();toast('Novo processo simulado criado')})}
  render();
}
