export const CATEGORIES = [
  {id:'civil',icon:'badge',title:'Documentos pessoais',desc:'Certidões, segundas vias e documentos de registro civil.'},
  {id:'notas',icon:'draw',title:'Notas & assinaturas',desc:'Firmas, autenticações, procurações, escrituras e atos notariais.'},
  {id:'imoveis',icon:'home_work',title:'Imóveis & registros',desc:'Matrículas, certidões, registros, averbações e regularização documental.'},
  {id:'rtdpj',icon:'domain',title:'Empresas, RTD & RCPJ',desc:'Contratos, documentos, pessoas jurídicas e registros empresariais.'},
  {id:'cobranca',icon:'receipt_long',title:'Protestos, cobranças & notificações',desc:'Pesquisa, protesto, notificações e negociação extrajudicial.'},
  {id:'familia',icon:'family_restroom',title:'Família & sucessões',desc:'Apoio documental em atos familiares e sucessórios extrajudiciais.'},
  {id:'mediacao',icon:'handshake',title:'Mediação & conciliação',desc:'Construção de acordos com procedimento organizado e atendimento humano.'},
  {id:'arbitragem',icon:'balance',title:'Arbitragem & Câmara',desc:'Administração de procedimentos arbitrais e estrutura privada de solução de conflitos.'},
  {id:'b2b',icon:'corporate_fare',title:'Planos para empresas',desc:'Operação recorrente para imobiliárias, condomínios, escolas e empresas.'},
  {id:'apoio',icon:'support_agent',title:'Pesquisa & apoio assistido',desc:'Quando o cliente não sabe onde ir, o que pedir ou prefere que alguém organize tudo.'}
];

const S=(id,category,icon,title,desc,from,channel,docs,steps,kind='assistido')=>({id,category,icon,title,desc,from,channel,docs,steps,kind});

export const SERVICES = [
  S('certidoes','civil','description','Certidões e 2ª vias','Nascimento, casamento, óbito e outras certidões de registro civil.',89,'Registro Civil / serventia competente',['Nome completo e filiação','Data e local aproximados do registro','Finalidade do documento'],['Triagem','Localização','Orçamento','Pedido','Acompanhamento','Entrega']),
  S('certidao-nascimento','civil','child_care','Certidão de nascimento','Segunda via, inteiro teor quando cabível e localização do registro.',89,'Registro Civil',['Nome completo','Filiação','Data e cidade de nascimento'],['Triagem','Localizar registro','Solicitar','Acompanhar','Entregar']),
  S('certidao-casamento','civil','favorite','Certidão de casamento','Segunda via, inteiro teor e pesquisa do cartório quando necessário.',99,'Registro Civil',['Nomes dos cônjuges','Data e cidade do casamento','Cartório, se souber'],['Triagem','Localização','Pedido','Acompanhamento','Entrega']),
  S('certidao-obito','civil','demography','Certidão de óbito','Segunda via e localização do registro de óbito.',89,'Registro Civil',['Nome do falecido','Data e cidade do óbito','Filiação, se souber'],['Triagem','Localização','Pedido','Entrega']),
  S('inteiro-teor','civil','article','Certidão em inteiro teor','Apoio para identificar quando o inteiro teor é necessário e solicitar a modalidade correta.',149,'Registro Civil / serventia',['Dados do registro','Finalidade','Documento do solicitante'],['Triagem','Conferência','Pedido','Entrega']),
  S('busca-registro-civil','civil','person_search','Busca de registro civil','Pesquisa quando a família não sabe em qual cartório está nascimento, casamento ou óbito.',129,'Centrais e serventias',['Tudo que souber sobre a pessoa','Datas aproximadas','Cidades prováveis'],['Entendimento','Pesquisa','Localização','Orçamento','Pedido']),

  S('assinaturas','notas','draw','Reconhecimento de firma','Triagem, conferência e encaminhamento para reconhecimento de firma.',49,'Tabelionato de Notas',['Documento original','Documento de identificação','Dados do signatário'],['Triagem','Conferência','Cartório indicado','Atendimento','Conclusão']),
  S('autenticacao','notas','verified','Autenticação de cópias','Organização e encaminhamento de documentos para autenticação.',49,'Tabelionato de Notas',['Documento original','Cópia ou arquivo','Documento do solicitante'],['Conferência','Encaminhamento','Ato notarial','Entrega']),
  S('assinatura-eletronica','notas','ink_pen','Assinatura eletrônica notarial','Orientação e acompanhamento de assinatura/reconhecimento em fluxo eletrônico oficial.',99,'e-Notariado / tabelionato',['Documento digital','Identificação das partes','Contato'],['Triagem','Cadastro','Assinatura','Validação','Entrega']),
  S('procuracoes','notas','contract_edit','Procuração pública','Preparação operacional, checklist e acompanhamento de procuração pública presencial ou eletrônica.',199,'Tabelionato / e-Notariado',['Documentos pessoais','Dados do procurador','Poderes pretendidos','Finalidade'],['Triagem','Checklist','Tabelionato','Minuta/ato','Assinatura','Entrega']),
  S('escritura','notas','contract','Escritura pública','Organização documental e acompanhamento do ato perante o tabelionato competente.',399,'Tabelionato de Notas',['Documentos das partes','Documentos do negócio','Certidões aplicáveis'],['Diagnóstico','Checklist','Orçamento','Tabelionato','Assinatura','Entrega']),
  S('ata-notarial','notas','fact_check','Ata notarial','Coleta inicial, organização de evidências e encaminhamento ao tabelionato.',249,'Tabelionato de Notas',['Identificação','Descrição do fato','Evidências disponíveis'],['Triagem','Organização','Tabelionato','Constatação','Entrega']),
  S('apostila-haia','notas','public','Apostila de Haia','Conferência, indicação de serventia habilitada, encaminhamento e acompanhamento.',129,'Serventia habilitada',['Documento a apostilar','País de destino','Finalidade'],['Conferência','Serventia','Apostilamento','Entrega']),
  S('aev','notas','flight_takeoff','Autorização eletrônica de viagem','Apoio ao fluxo de autorização de viagem para menor quando aplicável.',149,'e-Notariado / tabelionato',['Documentos dos responsáveis','Documento do menor','Dados da viagem'],['Triagem','Cadastro','Validação','Assinatura','Entrega']),
  S('testamento-apoio','notas','history_edu','Apoio para testamento público','Organização inicial e encaminhamento ao tabelião, sem substituir a orientação jurídica necessária.',299,'Tabelionato de Notas',['Documentos pessoais','Informações patrimoniais básicas','Vontades a relatar ao tabelião'],['Triagem','Checklist','Tabelionato','Ato','Arquivo']),

  S('imoveis','imoveis','home_work','Matrícula atualizada','Localização, solicitação e acompanhamento de matrícula atualizada.',149,'Registro de Imóveis / central eletrônica',['Endereço ou matrícula','Dados do proprietário','Finalidade'],['Triagem','Circunscrição','Pedido','Acompanhamento','Entrega']),
  S('pesquisa-matricula','imoveis','travel_explore','Pesquisa de matrícula','Descoberta do registro competente e pesquisa pelos dados disponíveis.',149,'Registro de Imóveis',['Endereço completo','Nome do proprietário','Dados antigos, se houver'],['Triagem','Circunscrição','Pesquisa','Localização','Entrega']),
  S('certidao-onus','imoveis','policy','Certidão de ônus','Solicitação de certidão para verificar registros, gravames e ônus existentes.',179,'Registro de Imóveis',['Matrícula','Cartório competente','Finalidade'],['Conferência','Pedido','Acompanhamento','Entrega']),
  S('certidoes-imobiliarias','imoveis','real_estate_agent','Pacote de certidões imobiliárias','Levantamento e organização das certidões necessárias para negócio ou regularização.',299,'Registro de Imóveis / órgãos',['Dados do imóvel','Dados das partes','Finalidade do pacote'],['Diagnóstico','Checklist','Solicitações','Conferência','Entrega']),
  S('registro-compra-venda','imoveis','key','Registro de compra e venda','Gestão documental e acompanhamento do título até o Registro de Imóveis.',499,'Tabelionato / Registro de Imóveis',['Título/escritura','Documentos das partes','Matrícula e certidões'],['Diagnóstico','Checklist','Protocolo','Exigências','Registro','Entrega']),
  S('averbacao','imoveis','edit_document','Averbação no Registro de Imóveis','Triagem, checklist e acompanhamento de averbações documentais.',349,'Registro de Imóveis',['Matrícula','Documento que fundamenta a averbação','Identificação'],['Triagem','Checklist','Protocolo','Exigências','Averbação']),
  S('retificacao-registro','imoveis','rule','Retificação de registro','Organização do procedimento e encaminhamento profissional quando necessário.',599,'Registro de Imóveis',['Matrícula','Documentos que mostram a divergência','Identificação'],['Diagnóstico','Documentos','Profissional se necessário','Protocolo','Acompanhamento']),
  S('cancelamento-onus','imoveis','lock_open','Cancelamento de ônus','Levantamento documental e acompanhamento do procedimento adequado para baixa de ônus.',449,'Registro de Imóveis',['Matrícula','Documento de quitação/cancelamento','Dados das partes'],['Diagnóstico','Checklist','Protocolo','Exigências','Baixa']),
  S('usucapiao-extrajudicial','imoveis','location_home','Usucapião extrajudicial - gestão documental','Coordenação documental, certidões e acompanhamento com advogado e registro competente.',1490,'Advogado / Tabelionato / Registro de Imóveis',['Documentos da posse','Planta/memorial quando aplicável','Certidões e documentos pessoais'],['Diagnóstico','Profissionais','Ata/documentos','Protocolo','Exigências','Registro'],'profissional'),
  S('adjudicacao-extrajudicial','imoveis','house_with_shield','Adjudicação compulsória extrajudicial - apoio','Triagem e coordenação documental com os profissionais obrigatórios.',1490,'Advogado / Registro de Imóveis',['Contrato/título','Comprovantes','Matrícula','Documentos das partes'],['Diagnóstico','Profissionais','Checklist','Protocolo','Exigências','Registro'],'profissional'),
  S('regularizacao-imovel','imoveis','architecture','Diagnóstico de regularização imobiliária','Mapa do que existe, do que falta e de quais profissionais ou órgãos serão necessários.',599,'Multicanal',['Tudo que o cliente tiver do imóvel','Endereço','Dados dos proprietários'],['Levantamento','Pesquisa','Diagnóstico','Plano de ação','Execução por etapas']),

  S('registro-contrato','rtdpj','contract','Registro de contrato no RTD','Organização e encaminhamento de contrato ou documento ao Registro de Títulos e Documentos.',179,'RTD',['Contrato/documento','Dados das partes','Finalidade'],['Triagem','Conferência','Protocolo','Exigências','Registro']),
  S('registro-documento','rtdpj','inventory','Registro e conservação de documento','Encaminhamento para registro, conservação e publicidade quando cabível.',179,'RTD',['Documento','Identificação do apresentante','Finalidade'],['Triagem','Conferência','Protocolo','Entrega']),
  S('notificacao-rtd','rtdpj','forward_to_inbox','Notificação via RTD','Preparação operacional e acompanhamento de notificação realizada pelo registro competente.',249,'RTD',['Documento base','Dados do destinatário','Endereço'],['Triagem','Conferência','Protocolo','Diligência','Certificação']),
  S('certidao-rtd','rtdpj','find_in_page','Certidão e pesquisa em RTD','Pesquisa, solicitação e acompanhamento de certidões e registros disponíveis.',149,'RTD',['Dados do documento ou parte','Período/local aproximado','Finalidade'],['Pesquisa','Pedido','Acompanhamento','Entrega']),
  S('registro-associacao','rtdpj','groups','Registro de associação / entidade','Organização de estatuto, atas e documentos para protocolo no RCPJ, com apoio profissional quando necessário.',499,'Registro Civil de Pessoas Jurídicas',['Estatuto','Ata','Qualificação dos responsáveis'],['Checklist','Conferência','Protocolo','Exigências','Registro'],'profissional'),
  S('alteracao-rCPJ','rtdpj','edit_square','Alteração de pessoa jurídica no RCPJ','Acompanhamento de alteração de estatuto, diretoria, endereço ou outros atos registráveis.',399,'Registro Civil de Pessoas Jurídicas',['Ato/ata de alteração','Documentos da entidade','Representação'],['Triagem','Checklist','Protocolo','Exigências','Registro']),
  S('certidoes-empresa','rtdpj','business_center','Certidões empresariais','Pesquisa e organização de certidões cadastrais e registrais da empresa.',199,'Junta / RCPJ / órgãos',['CNPJ ou dados da entidade','Finalidade','UF/município'],['Pesquisa','Solicitação','Organização','Entrega']),

  S('protestos','cobranca','gavel','Consulta e certidão de protesto','Pesquisa de protestos e obtenção das certidões disponíveis.',99,'Tabelionatos / central de protesto',['CPF/CNPJ','Nome','Praça quando necessária'],['Consulta','Confirmação','Certidão','Entrega']),
  S('encaminhar-protesto','cobranca','send_money','Encaminhamento para protesto','Organização do título e envio ao canal competente, quando admissível.',249,'Tabelionato de Protesto',['Título/documento da dívida','Dados do devedor','Valor e vencimento'],['Triagem','Conferência','Protocolo','Acompanhamento'],'assistido'),
  S('cancelar-protesto','cobranca','playlist_remove','Cancelamento de protesto','Orientação documental e acompanhamento do cancelamento perante o tabelionato.',249,'Tabelionato de Protesto',['Dados do protesto','Comprovante/carta de anuência quando aplicável','Identificação'],['Diagnóstico','Checklist','Pedido','Cancelamento']),
  S('notificacao-cobranca','cobranca','mark_email_unread','Notificação de cobrança','Comunicação formal de dívida com tentativa de regularização antes de medidas posteriores.',199,'CNJP / RTD quando solicitado',['Origem da dívida','Valor','Dados do devedor'],['Conferência','Notificação','Contato','Negociação','Resultado']),
  S('notificacao-acordo','cobranca','mark_email_read','Convocação para acordo','Convite formal para negociação, conciliação ou mediação.',199,'CNJP / RTD',['Dados das partes','Resumo do conflito','Forma de contato'],['Triagem','Convocação','Sessão/negociação','Resultado']),
  S('notificacao-contratual','cobranca','contract_delete','Notificação contratual','Organização e encaminhamento de comunicação sobre obrigação, descumprimento ou encerramento.',299,'CNJP / RTD / profissional quando necessário',['Contrato','Fato ocorrido','Dados da outra parte'],['Triagem','Revisão necessária','Notificação','Comprovação'],'profissional'),
  S('notificacao-desocupacao','cobranca','door_open','Notificação de desocupação','Organização do caso e encaminhamento da comunicação adequada à situação locatícia.',299,'CNJP / RTD / profissional quando necessário',['Contrato de locação','Dados do imóvel e partes','Motivo'],['Triagem','Conferência','Notificação','Acompanhamento'],'profissional'),
  S('negociacao-divida','cobranca','payments','Negociação extrajudicial de dívida','Contato estruturado, proposta, contraproposta e registro do acordo alcançado.',249,'CNJP / Câmara',['Comprovantes da dívida','Valores','Contato das partes'],['Triagem','Contato','Negociação','Acordo','Acompanhamento']),
  S('recuperacao-amigavel','cobranca','account_balance_wallet','Cobrança amigável recorrente','Operação de cobrança não judicial para carteiras de pequenas empresas.',690,'CNJP B2B',['Relação de devedores','Documentos da dívida','Política de negociação'],['Importação','Contato','Negociação','Relatório','Encaminhamento']),

  S('divorcio-extrajudicial','familia','heart_broken','Divórcio extrajudicial - coordenação documental','Organização de documentos, certidões e agenda com advogado e tabelionato quando o caso comportar via extrajudicial.',790,'Advogado / Tabelionato',['Documentos do casal','Certidão de casamento','Informações patrimoniais'],['Triagem','Advogado','Checklist','Tabelionato','Escritura','Entrega'],'profissional'),
  S('inventario-extrajudicial','familia','deceased','Inventário extrajudicial - coordenação documental','Gestão de documentos, certidões e fluxo com advogado, tributos e tabelionato.',1490,'Advogado / Tabelionato / órgãos fiscais',['Certidão de óbito','Documentos dos herdeiros','Bens e dívidas','Certidões'],['Diagnóstico','Advogado','Levantamento','Tributos','Escritura','Registros'],'profissional'),
  S('uniao-estavel','familia','diversity_1','Escritura de união estável','Triagem e organização documental para formalização perante tabelionato.',299,'Tabelionato / profissional quando necessário',['Documentos pessoais','Dados do casal','Informações patrimoniais'],['Triagem','Checklist','Tabelionato','Assinatura','Entrega']),
  S('pacto-antenupcial','familia','favorite_border','Pacto antenupcial - apoio documental','Organização do fluxo entre orientação jurídica, tabelionato e registro quando aplicável.',399,'Advogado / Tabelionato / Registro',['Documentos do casal','Regime pretendido após orientação','Dados do casamento'],['Triagem','Orientação jurídica','Tabelionato','Registro'],'profissional'),
  S('emancipacao','familia','person_raised_hand','Emancipação voluntária - apoio','Checklist e encaminhamento para escritura e registro quando cabível.',299,'Tabelionato / Registro Civil',['Documentos dos responsáveis','Documento do menor','Certidões'],['Triagem','Checklist','Tabelionato','Registro','Entrega']),

  S('mediacao-geral','mediacao','handshake','Mediação extrajudicial','Terceiro imparcial organiza o diálogo para as partes construírem uma solução consensual.',390,'Câmara CNJP',['Identificação das partes','Resumo do conflito','Documentos relevantes'],['Triagem','Convite','Sessão','Construção do acordo','Termo']),
  S('conciliacao','mediacao','diversity_3','Conciliação extrajudicial','Sessão direcionada à construção de uma proposta de acordo prática.',290,'Câmara CNJP',['Dados das partes','Resumo objetivo','Valores/documentos quando houver'],['Triagem','Convocação','Sessão','Proposta','Termo']),
  S('mediacao-familiar','mediacao','family_restroom','Mediação familiar','Conflitos de convivência, comunicação, responsabilidades e questões patrimoniais disponíveis.',490,'Câmara CNJP / profissional quando necessário',['Dados das partes','Resumo do conflito','Documentos úteis'],['Triagem','Admissibilidade','Sessões','Acordo/encaminhamento'],'profissional'),
  S('mediacao-condominio','mediacao','apartment','Mediação condominial','Conflitos entre moradores, síndico, condomínio, fornecedores ou administração.',490,'Câmara CNJP',['Convenção/regimento quando relevante','Relato das partes','Documentos do conflito'],['Triagem','Convocação','Sessão','Acordo','Registro']),
  S('mediacao-vizinhanca','mediacao','holiday_village','Mediação de vizinhança','Barulho, uso de áreas, limites, convivência e outros conflitos negociáveis.',390,'Câmara CNJP',['Relato','Contatos','Evidências úteis'],['Triagem','Convocação','Mediação','Acordo']),
  S('mediacao-escolar','mediacao','school','Mediação escolar','Conflitos entre alunos, pais, professores e instituição, respeitando limites legais e de proteção.',690,'Câmara CNJP / escola',['Relato do conflito','Participantes','Políticas internas quando houver'],['Triagem','Admissibilidade','Convocação','Sessão','Plano/acordo']),
  S('mediacao-empresarial','mediacao','business_center','Mediação empresarial','Conflitos entre sócios, fornecedores, clientes ou parceiros comerciais.',790,'Câmara CNJP',['Contratos','Resumo do conflito','Dados dos representantes'],['Triagem','Convocação','Sessões','Acordo']),
  S('mediacao-locaticia','mediacao','real_estate_agent','Mediação locatícia','Negociação de aluguel, entrega de imóvel, reparos, garantias e obrigações disponíveis.',490,'Câmara CNJP',['Contrato','Comprovantes','Resumo do problema'],['Triagem','Convocação','Sessão','Acordo']),
  S('mediacao-consumidor','mediacao','shopping_cart','Mediação de consumo','Tentativa estruturada de acordo entre consumidor e fornecedor.',390,'Câmara CNJP',['Comprovantes','Contrato/nota','Histórico do problema'],['Triagem','Convocação','Mediação','Acordo']),
  S('audiencia-online','mediacao','video_chat','Sessão online de mediação/conciliação','Videoconferência organizada com agenda, participantes e registro administrativo do procedimento.',290,'Câmara CNJP',['Dados das partes','E-mails/telefones','Resumo do caso'],['Agendamento','Convites','Sessão','Registro','Resultado']),

  S('arbitragem','arbitragem','balance','Administração de arbitragem','A Câmara organiza secretaria, comunicações, documentos, agenda e atos do procedimento arbitral.',990,'Câmara CNJP / árbitro',['Convenção arbitral','Contrato','Dados das partes','Resumo da controvérsia'],['Protocolo','Admissibilidade','Constituição do tribunal','Instrução','Sentença arbitral'],'camara'),
  S('arbitragem-empresarial','arbitragem','corporate_fare','Arbitragem empresarial','Administração de conflitos patrimoniais disponíveis entre empresas.',1490,'Câmara CNJP / árbitro',['Contrato','Cláusula compromissória','Documentos do conflito'],['Protocolo','Contraditório','Árbitro','Instrução','Sentença'],'camara'),
  S('arbitragem-contratual','arbitragem','description','Arbitragem contratual','Procedimento para controvérsias patrimoniais decorrentes de contratos com convenção arbitral.',1290,'Câmara CNJP / árbitro',['Contrato','Convenção arbitral','Provas iniciais'],['Protocolo','Constituição','Defesas','Instrução','Sentença'],'camara'),
  S('arbitragem-societaria','arbitragem','groups_2','Arbitragem societária','Administração de conflitos patrimoniais disponíveis entre sócios ou sociedades.',1790,'Câmara CNJP / árbitro',['Contrato/estatuto','Acordo de sócios','Documentos da controvérsia'],['Triagem','Protocolo','Tribunal arbitral','Instrução','Sentença'],'camara'),
  S('arbitragem-imobiliaria','arbitragem','location_city','Arbitragem imobiliária','Conflitos patrimoniais disponíveis ligados a contratos imobiliários e negócios privados.',1490,'Câmara CNJP / árbitro',['Contrato','Documentos do imóvel/negócio','Convenção arbitral'],['Admissibilidade','Protocolo','Instrução','Sentença'],'camara'),
  S('arbitragem-locacao','arbitragem','key','Arbitragem em contratos de locação','Administração de controvérsias patrimoniais disponíveis quando existir convenção de arbitragem válida.',1290,'Câmara CNJP / árbitro',['Contrato de locação','Convenção arbitral','Comprovantes'],['Triagem','Protocolo','Defesa','Instrução','Sentença'],'camara'),
  S('secretaria-arbitral','arbitragem','folder_managed','Secretaria de procedimento arbitral','Organização de autos digitais, comunicações, prazos, agenda, atas administrativas e suporte ao árbitro.',790,'Câmara CNJP',['Dados do procedimento','Partes e representantes','Calendário processual'],['Cadastro','Comunicações','Prazos','Audiências','Arquivo'],'camara'),
  S('audiencia-arbitral','arbitragem','video_camera_front','Audiência arbitral online','Infraestrutura de videoconferência, convites, sala, documentos e apoio administrativo.',490,'Câmara CNJP',['Número do procedimento','Participantes','Agenda','Documentos'],['Agendamento','Convites','Sala','Audiência','Registro'],'camara'),
  S('compromisso-arbitral','arbitragem','edit_note','Apoio à formalização da convenção arbitral','Organização administrativa da cláusula ou compromisso, com revisão jurídica quando necessária.',390,'Câmara / profissional habilitado',['Contrato ou conflito','Dados das partes','Intenção de submeter à arbitragem'],['Triagem','Minuta-base','Revisão jurídica','Assinatura','Arquivo'],'profissional'),

  S('plano-imobiliaria','b2b','real_estate_agent','Plano para imobiliárias','Central recorrente para matrículas, certidões, notificações, registros e acompanhamento de clientes.',990,'CNJP B2B',['Cadastro da imobiliária','Responsáveis','Tipos de demanda'],['Onboarding','Fila de pedidos','Protocolos','Relatórios','Faturamento']),
  S('plano-condominio','b2b','apartment','Plano para condomínios','Notificações, mediação, documentos, certidões e apoio burocrático recorrente.',890,'CNJP B2B / Câmara',['Dados do condomínio','Síndico/administradora','Tipos de demanda'],['Onboarding','Chamados','Mediação/documentos','Relatório']),
  S('plano-escolas','b2b','school','Plano para escolas','Mediação, gestão de conflitos, notificações e apoio documental para instituições de ensino.',990,'CNJP B2B / Câmara',['Dados da escola','Responsáveis','Políticas internas'],['Diagnóstico','Fluxo de casos','Sessões','Relatórios','Revisão']),
  S('plano-empresas','b2b','business','Central extrajudicial para empresas','Fila única para certidões, notificações, registros, cobranças, mediações e documentos corporativos.',1190,'CNJP B2B',['Dados da empresa','Responsáveis','Demandas recorrentes'],['Onboarding','Fila','Execução','Relatório','Faturamento']),
  S('plano-escritorios','b2b','work','Backoffice para escritórios e profissionais','Pesquisa, certidões, protocolos e acompanhamento operacional para quem precisa terceirizar burocracia.',990,'CNJP B2B',['Cadastro do parceiro','Responsáveis','Escopo contratado'],['Onboarding','Pedidos','Execução','SLA','Relatório']),

  S('localizar-cartorio','apoio','pin_drop','Localizar cartório ou serventia','Descobrir qual serventia atende o caso e quais canais existem.',79,'Pesquisa multicanal',['O que precisa resolver','Cidade/estado','Dados disponíveis'],['Entendimento','Pesquisa','Indicação','Próximo passo']),
  S('pesquisas','apoio','manage_search','Pesquisa documental','Quando você não sabe onde está o registro, matrícula ou documento.',129,'Pesquisa multicanal',['Tudo que souber sobre o caso','Nomes e datas aproximadas','Cidade/estado provável'],['Entendimento','Hipóteses','Pesquisa','Localização','Orçamento']),
  S('diagnostico-documental','apoio','fact_check','Diagnóstico documental','Organizamos a papelada e mostramos o que existe, o que falta e qual é o próximo passo.',199,'CNJP',['Documentos disponíveis','Objetivo do cliente'],['Recebimento','Classificação','Pesquisa','Checklist','Plano']),
  S('digitalizacao','apoio','document_scanner','Digitalização e pasta documental','Transformação de papéis em arquivos organizados, nomeados e vinculados ao processo.',79,'CNJP',['Documentos físicos'],['Recepção','Digitalização','Classificação','Conferência','Entrega']),
  S('protocolo-acompanhamento','apoio','task_alt','Protocolo e acompanhamento','Serviço operacional para protocolar, registrar número, acompanhar prazo e cobrar andamento.',149,'Órgão / serventia competente',['Pedido/documento','Dados do interessado','Canal competente'],['Conferência','Protocolo','Registro','Acompanhamento','Entrega']),
  S('retirada-entrega','apoio','local_shipping','Retirada e entrega assistida','Apoio logístico para cliente que não quer ou não consegue lidar com retirada, impressão e entrega física.',59,'CNJP / parceiro logístico',['Endereço','Documento/pedido','Pessoa autorizada'],['Agendamento','Retirada','Conferência','Entrega']),
  S('outros','apoio','support_agent','Não sei o que preciso','Conte o problema em linguagem normal. Um atendente organiza o caminho e sugere o serviço certo.',0,'Triagem humana assistida',['Só conte o que aconteceu'],['Conversa','Diagnóstico operacional','Checklist','Encaminhamento'])
];

export const CASES = [
  {id:'CD-1087',client:'João Batista',age:83,service:'assinaturas',title:'Reconhecimento de firma',channel:'Balcão / humano',owner:'Fran',status:'coleta',priority:'normal',amount:78,official:28,fee:50,created:'Hoje 09:14',deadline:'Hoje',phone:'(11) 9 8123-4401',notes:'Cliente prefere atendimento por telefone. Filho enviará foto do documento.',docs:[['RG','ok'],['Documento para assinatura','waiting']],timeline:['Atendimento iniciado no balcão','RG conferido','Aguardando documento original']},
  {id:'CD-1086',client:'Mariana Alves',age:34,service:'certidoes',title:'2ª via de certidão de casamento',channel:'Triagem digital',owner:'Paula',status:'protocolado',priority:'normal',amount:168,official:68,fee:100,created:'Hoje 08:42',deadline:'29/08',phone:'(11) 9 9222-1840',notes:'Casamento em Guarulhos, 2014.',docs:[['Documento de identificação','ok'],['Dados do casamento','ok'],['Comprovante de pagamento','ok']],timeline:['Triagem digital concluída','Pagamento aprovado','Pedido protocolado #RC-884291']},
  {id:'CD-1085',client:'Carlos Nogueira',age:51,service:'imoveis',title:'Matrícula atualizada de imóvel',channel:'WhatsApp',owner:'Fran',status:'analise',priority:'high',amount:315,official:165,fee:150,created:'Ontem 16:20',deadline:'28/08',phone:'(11) 9 7311-9910',notes:'Cliente não sabe o número da matrícula. Endereço completo disponível.',docs:[['RG','ok'],['Endereço completo','ok'],['Matrícula','missing']],timeline:['WhatsApp recebido','Triagem humana concluída','Circunscrição identificada','Em pesquisa de matrícula']},
  {id:'CD-1084',client:'Escola Horizonte',age:null,service:'notificacao-rtd',title:'Notificação extrajudicial',channel:'Site',owner:'Daniel',status:'exigencia',priority:'high',amount:690,official:190,fee:500,created:'25/08 13:07',deadline:'27/08',phone:'(11) 4432-1100',notes:'Pessoa jurídica. Documento base precisa de nova assinatura.',docs:[['Contrato','ok'],['Representação da empresa','ok'],['Documento assinado','missing']],timeline:['Solicitação recebida','Documentos conferidos','Protocolo realizado','Exigência recebida: assinatura inválida']},
  {id:'CD-1083',client:'Aline Souza',age:29,service:'procuracoes',title:'Procuração eletrônica',channel:'Triagem digital',owner:'Fran',status:'aguardando',priority:'normal',amount:430,official:230,fee:200,created:'25/08 10:31',deadline:'30/08',phone:'(11) 9 6118-0234',notes:'Aguardando videoconferência/ato no canal oficial.',docs:[['RG','ok'],['CPF','ok'],['Dados do procurador','ok'],['Minuta/dados do ato','ok']],timeline:['Triagem concluída','Checklist aprovado','Orçamento pago','Encaminhado ao tabelionato']},
  {id:'CD-1082',client:'Roberto Lima',age:62,service:'certidoes',title:'Certidão de óbito',channel:'Telefone',owner:'Paula',status:'entregue',priority:'normal',amount:145,official:65,fee:80,created:'23/08 11:44',deadline:'Concluído',phone:'(11) 2456-7780',notes:'Cliente sem WhatsApp. Entrega impressa retirada no balcão.',docs:[['Dados do falecido','ok'],['Documento solicitante','ok']],timeline:['Atendimento por telefone','Cartório localizado','Pagamento presencial','Certidão emitida','Retirada no balcão']},
  {id:'CA-0214',client:'Condomínio Bosque Azul',age:null,service:'mediacao-condominio',title:'Mediação condominial',channel:'WhatsApp',owner:'Fran',status:'aguardando',priority:'normal',amount:790,official:0,fee:790,created:'Hoje 11:20',deadline:'02/09',phone:'(11) 4002-5511',notes:'Conflito entre morador e administração por uso de área comum.',docs:[['Convenção do condomínio','ok'],['Relato do síndico','ok'],['Contato do morador','ok']],timeline:['Triagem recebida','Caso admitido para mediação','Convite enviado','Aguardando confirmação da outra parte']},
  {id:'CA-0213',client:'Alfa Serviços LTDA',age:null,service:'arbitragem-contratual',title:'Arbitragem contratual',channel:'Site',owner:'Fran',status:'analise',priority:'high',amount:2490,official:0,fee:2490,created:'Ontem 14:05',deadline:'03/09',phone:'(11) 3333-2222',notes:'Contrato possui cláusula compromissória. Simulação de procedimento arbitral.',docs:[['Contrato','ok'],['Cláusula compromissória','ok'],['Notificação da controvérsia','ok']],timeline:['Requerimento recebido','Documentos conferidos','Em análise de admissibilidade']}
];

export const STATUS = {
  novo:{label:'Novo',icon:'fiber_new'},coleta:{label:'Coletando documentos',icon:'inventory_2'},analise:{label:'Em análise',icon:'search_check'},aguardando:{label:'Aguardando terceiro',icon:'hourglass_top'},protocolado:{label:'Protocolado',icon:'task_alt'},exigencia:{label:'Exigência',icon:'warning'},entregue:{label:'Entregue',icon:'verified'}
};

export const AUTOMATIONS = [
  ['Triagem inteligente','Interpreta a solicitação e sugere serviço/checklist','Ativa'],
  ['OCR de documentos','Extrai nomes, CPF, datas, matrículas e cartórios','Simulada'],
  ['Cobrança automática','Gera cobrança separando taxa oficial e serviço operacional','Simulada'],
  ['Atualização por WhatsApp','Avisa cada mudança relevante de status','Simulada'],
  ['Leitura de exigências','Resume devolutivas em tarefas objetivas para o operador','Simulada'],
  ['Controle de prazo','Alerta processos próximos do vencimento','Ativa'],
  ['Portal do cliente','Linha do tempo, arquivos, valores e protocolo','Ativa'],
  ['RPA assistido','Preenche dados repetitivos em portais, com revisão humana antes do envio','Planejada'],
  ['Assistente de serviço por IA','Cliente descreve o problema e recebe sugestões de serviços adequados','Planejada'],
  ['Secretaria arbitral digital','Organiza prazos, comunicações, documentos e audiências do procedimento','Simulada']
];
