export const SERVICES = [
  {id:'certidoes',icon:'description',title:'Certidões e 2ª vias',desc:'Nascimento, casamento, óbito, protesto, matrícula e outras certidões.',from:89,channel:'Centrais oficiais / serventias',docs:['Dados da pessoa ou imóvel','Finalidade do documento','Local do registro, se souber'],steps:['Triagem','Localização','Orçamento','Protocolo','Acompanhamento','Entrega']},
  {id:'assinaturas',icon:'draw',title:'Firmas e autenticações',desc:'Orientação, preparação e encaminhamento para reconhecimento de firma e autenticação.',from:49,channel:'Tabelionato de Notas',docs:['Documento original','Documento de identificação','Dados do signatário'],steps:['Triagem','Conferência','Cartório indicado','Atendimento/encaminhamento','Conclusão']},
  {id:'procuracoes',icon:'contract_edit',title:'Procurações e atos notariais',desc:'Preparação operacional e acompanhamento de procurações, escrituras, atas e atos eletrônicos.',from:199,channel:'Tabelionato / e-Notariado',docs:['Documentos pessoais','Dados das partes','Finalidade do ato','Documentos do negócio'],steps:['Triagem','Checklist','Pré-análise','Cartório','Assinatura','Entrega']},
  {id:'imoveis',icon:'home_work',title:'Imóveis e registros',desc:'Matrículas, certidões, pesquisas, protocolos, averbações e acompanhamento registral.',from:149,channel:'Registro de Imóveis / central eletrônica',docs:['Endereço ou matrícula','Dados do proprietário','Documento de identificação','Finalidade'],steps:['Triagem','Circunscrição','Documentos','Protocolo','Exigências','Registro/entrega']},
  {id:'protestos',icon:'gavel',title:'Protestos e notificações',desc:'Pesquisas, certidões, notificações extrajudiciais e acompanhamento de procedimentos.',from:99,channel:'Tabelionatos / RTD',docs:['Dados das partes','Documento base','Endereço','Finalidade'],steps:['Triagem','Conferência','Orçamento','Protocolo','Diligência','Resultado']},
  {id:'empresas',icon:'domain',title:'RTD e pessoas jurídicas',desc:'Registros documentais, certidões, notificações e apoio operacional a pessoas jurídicas.',from:179,channel:'RTD / Registro Civil de PJ',docs:['Documento societário','Dados da empresa','Representantes','Finalidade'],steps:['Triagem','Checklist','Validação','Protocolo','Exigências','Entrega']},
  {id:'pesquisas',icon:'manage_search',title:'Pesquisas documentais',desc:'Quando você não sabe onde está o registro ou qual documento precisa.',from:129,channel:'Pesquisa multicanal',docs:['Tudo que souber sobre o caso','Nomes e datas aproximadas','Cidade/estado provável'],steps:['Entendimento','Hipóteses','Pesquisa','Localização','Orçamento','Solicitação']},
  {id:'outros',icon:'support_agent',title:'Não sei o que preciso',desc:'Conte o problema em linguagem normal. Um atendente organiza o caminho.',from:0,channel:'Triagem humana assistida',docs:['Só conte o que aconteceu'],steps:['Conversa','Diagnóstico operacional','Checklist','Encaminhamento']}
];

export const CASES = [
  {id:'CD-1087',client:'João Batista',age:83,service:'assinaturas',title:'Reconhecimento de firma',channel:'Balcão / humano',owner:'Fran',status:'coleta',priority:'normal',amount:78,official:28,fee:50,created:'Hoje 09:14',deadline:'Hoje',phone:'(11) 9 8123-4401',notes:'Cliente prefere atendimento por telefone. Filho enviará foto do documento.',docs:[['RG','ok'],['Documento para assinatura','waiting']],timeline:['Atendimento iniciado no balcão','RG conferido','Aguardando documento original']},
  {id:'CD-1086',client:'Mariana Alves',age:34,service:'certidoes',title:'2ª via de certidão de casamento',channel:'Triagem digital',owner:'Paula',status:'protocolado',priority:'normal',amount:168,official:68,fee:100,created:'Hoje 08:42',deadline:'29/08',phone:'(11) 9 9222-1840',notes:'Casamento em Guarulhos, 2014.',docs:[['Documento de identificação','ok'],['Dados do casamento','ok'],['Comprovante de pagamento','ok']],timeline:['Triagem digital concluída','Pagamento aprovado','Pedido protocolado #RC-884291']},
  {id:'CD-1085',client:'Carlos Nogueira',age:51,service:'imoveis',title:'Matrícula atualizada de imóvel',channel:'WhatsApp',owner:'Fran',status:'analise',priority:'high',amount:315,official:165,fee:150,created:'Ontem 16:20',deadline:'28/08',phone:'(11) 9 7311-9910',notes:'Cliente não sabe o número da matrícula. Endereço completo disponível.',docs:[['RG','ok'],['Endereço completo','ok'],['Matrícula','missing']],timeline:['WhatsApp recebido','Triagem humana concluída','Circunscrição identificada','Em pesquisa de matrícula']},
  {id:'CD-1084',client:'Escola Horizonte',age:null,service:'protestos',title:'Notificação extrajudicial',channel:'Site',owner:'Daniel',status:'exigencia',priority:'high',amount:690,official:190,fee:500,created:'25/08 13:07',deadline:'27/08',phone:'(11) 4432-1100',notes:'Pessoa jurídica. Documento base precisa de nova assinatura.',docs:[['Contrato','ok'],['Representação da empresa','ok'],['Documento assinado','missing']],timeline:['Solicitação recebida','Documentos conferidos','Protocolo realizado','Exigência recebida: assinatura inválida']},
  {id:'CD-1083',client:'Aline Souza',age:29,service:'procuracoes',title:'Procuração eletrônica',channel:'Triagem digital',owner:'Fran',status:'aguardando',priority:'normal',amount:430,official:230,fee:200,created:'25/08 10:31',deadline:'30/08',phone:'(11) 9 6118-0234',notes:'Aguardando videoconferência/ato no canal oficial.',docs:[['RG','ok'],['CPF','ok'],['Dados do procurador','ok'],['Minuta/dados do ato','ok']],timeline:['Triagem concluída','Checklist aprovado','Orçamento pago','Encaminhado ao tabelionato']},
  {id:'CD-1082',client:'Roberto Lima',age:62,service:'certidoes',title:'Certidão de óbito',channel:'Telefone',owner:'Paula',status:'entregue',priority:'normal',amount:145,official:65,fee:80,created:'23/08 11:44',deadline:'Concluído',phone:'(11) 2456-7780',notes:'Cliente sem WhatsApp. Entrega impressa retirada no balcão.',docs:[['Dados do falecido','ok'],['Documento solicitante','ok']],timeline:['Atendimento por telefone','Cartório localizado','Pagamento presencial','Certidão emitida','Retirada no balcão']}
];

export const STATUS = {
  novo:{label:'Novo',icon:'fiber_new'},coleta:{label:'Coletando documentos',icon:'inventory_2'},analise:{label:'Em análise',icon:'search_check'},aguardando:{label:'Aguardando terceiro',icon:'hourglass_top'},protocolado:{label:'Protocolado',icon:'task_alt'},exigencia:{label:'Exigência',icon:'warning'},entregue:{label:'Entregue',icon:'verified'}
};

export const AUTOMATIONS = [
  ['Triagem inteligente','Interpreta a solicitação e sugere serviço/checklist','Ativa'],
  ['OCR de documentos','Extrai nomes, CPF, datas, matrículas e cartórios','Simulada'],
  ['Cobrança automática','Gera cobrança separando taxa oficial e honorário operacional','Simulada'],
  ['Atualização por WhatsApp','Avisa cada mudança relevante de status','Simulada'],
  ['Leitura de exigências','Resume devolutivas em tarefas objetivas para o operador','Simulada'],
  ['Controle de prazo','Alerta processos próximos do vencimento','Ativa'],
  ['Portal do cliente','Linha do tempo, arquivos, valores e protocolo','Ativa'],
  ['RPA assistido','Preenche dados repetitivos em portais, com revisão humana antes do envio','Planejada']
];
