(()=>{
  const desktopSteps=[
    {selector:'#adminNav',title:'Menu principal',text:'Use o menu para alternar entre visão geral, atendimentos, processos, documentos, financeiro e catálogo.'},
    {selector:'#adminContent .panel',title:'Área de trabalho',text:'Cada tela mostra os dados reais do sistema. Em Atendimentos, filtre, ordene e abra tickets.'},
    {selector:'#simulateHuman',title:'Novo atendimento humano',text:'Cria um ticket para contato por balcão, telefone ou WhatsApp e o coloca na fila.'},
    {selector:'#simulateDigital',title:'Nova triagem digital',text:'Abre uma entrada para a triagem assistida por IA local. A sugestão sempre precisa de revisão humana.'},
    {selector:'.admin-sidebar .sidebar-foot a[href="./manual.html"]',title:'Manual operacional',text:'Consulte o Manual para entender a ordem das etapas e as consequências de cada decisão.'}
  ];
  const mobileSteps=[
    {selector:'#menuToggle',title:'Abrir o menu',text:'No celular, toque aqui para abrir as áreas do sistema.'},
    {selector:'#adminContent .panel',title:'Área de trabalho',text:'Esta área mostra os dados reais. Em Atendimentos, os tickets aparecem em cards próprios para toque.'},
    {selector:'.tutorial-mobile-launch',title:'Tutorial',text:'Este botão abre novamente o guia sempre que precisar.'},
    {selector:'.admin-sidebar .sidebar-foot a[href="./manual.html"]',title:'Manual operacional',text:'O Manual explica a ordem das etapas e as consequências de cada decisão.'}
  ];
  const steps=matchMedia('(max-width:700px)').matches?mobileSteps:desktopSteps;
  const css=document.createElement('style');css.textContent='.tutorial-overlay{position:fixed;inset:0;z-index:3000;background:rgba(15,23,42,.72)}.tutorial-focus{position:fixed;z-index:3001;border:3px solid #2dd4bf;border-radius:12px;box-shadow:0 0 0 9999px rgba(15,23,42,.72);pointer-events:none;transition:all .2s}.tutorial-card{position:fixed;z-index:3002;max-width:330px;background:#fff;border-radius:16px;padding:18px;box-shadow:0 18px 50px #0006;color:#101828}.tutorial-card h2{font-size:18px;margin:0 0 8px}.tutorial-card p{font-size:14px;line-height:1.45;margin:0 0 14px;color:#475467}.tutorial-card .tutorial-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.tutorial-card button{border:1px solid #d0d5dd;border-radius:9px;background:#fff;padding:9px 12px;font-weight:700;cursor:pointer}.tutorial-card button.primary{background:#0f766e;color:#fff;border-color:#0f766e}.tutorial-launch{white-space:nowrap}.tutorial-mobile-launch{display:none}@media(max-width:700px){.tutorial-mobile-launch{display:block;position:fixed;right:16px;bottom:16px;z-index:2000;border:0;border-radius:999px;background:#0f766e;color:#fff;padding:12px 15px;font-weight:800;box-shadow:0 5px 18px #10182844}.tutorial-card{left:16px;right:16px;bottom:18px;max-width:none}.tutorial-focus{max-width:calc(100vw - 24px)}}';document.head.append(css);
  const start=()=>{let i=0,over=document.createElement('div');over.className='tutorial-overlay';let focus=document.createElement('div');focus.className='tutorial-focus';let card=document.createElement('div');card.className='tutorial-card';document.body.append(over,focus,card);const close=()=>{over.remove();focus.remove();card.remove()};const draw=()=>{const s=steps[i],el=document.querySelector(s.selector);if(!el){if(i<steps.length-1){i++;return draw()}return close()}el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{const r=el.getBoundingClientRect();focus.style.left=r.left-6+'px';focus.style.top=r.top-6+'px';focus.style.width=r.width+12+'px';focus.style.height=r.height+12+'px';card.innerHTML='<h2>'+s.title+'</h2><p>'+s.text+'</p><div class="tutorial-actions"><button class="tutorial-close">Sair</button><button class="tutorial-prev" '+(i?'':'disabled')+'>Anterior</button><button class="primary tutorial-next">'+(i===steps.length-1?'Concluir':'Próximo')+'</button></div>';card.querySelector('.tutorial-close').onclick=close;card.querySelector('.tutorial-prev').onclick=()=>{if(i){i--;draw()}};card.querySelector('.tutorial-next').onclick=()=>{if(i===steps.length-1)close();else{i++;draw()}}},220)};draw()};
  const add=()=>{if(!document.querySelector('.tutorial-launch')){const b=document.createElement('button');b.className='btn secondary small tutorial-launch';b.type='button';b.textContent='▶ Tutorial';b.onclick=start;document.querySelector('.admin-top-actions')?.prepend(b)}if(!document.querySelector('.tutorial-mobile-launch')){const b=document.createElement('button');b.className='tutorial-mobile-launch';b.type='button';b.textContent='▶ Tutorial';b.setAttribute('aria-label','Abrir tutorial');b.onclick=start;document.body.append(b)}};new MutationObserver(add).observe(document.body,{childList:true,subtree:true});add();window.startAdminTutorial=start;
})();
